index:
    path: /
    controller: Zaprogramowani\Infra\Controller\DataController::index

getData:
    path: /api/data
    controller: Zaprogramowani\Infra\Controller\DataController::getData

api_login_check:
    path: /api/login_check
