index:
    path: /
    controller: Zaprogramowani\Infra\Controller\DataController::index

getData:
    path: /api/data
    controller: Zaprogramowani\Infra\Controller\DataController::getData

getUserData:
    path: /api/user/data
    controller: Zaprogramowani\Infra\Controller\DataController::getUserHistoricalData

register:
    path: /api/register
    methods: [POST]
    controller: Zaprogramowani\Infra\Controller\UserController::register

api_login_check:
    path: /api/login_check
